#!/usr/bin/env python3
"""
Canonical part-of-speech normalizer.

Word content is generated by LLM agents (tools/gen_lang_content.py) and imported
from spreadsheets (tools/import_content.py). Both produce a free-text `pos` that
drifts wildly for the same concept — "noun", "noun-m", "noun masc.", "noun_f",
"n.m.", "adj.", "danh từ" (Vietnamese for noun) all show up. The app needs a
stable, language-neutral tag to look up a translated label, plus the grammatical
gender when the source encoded it.

`normalize(raw) -> (tag, gender)`:
  tag    one of TAGS (below); unknown input falls through to "other".
  gender "m" | "f" | "n" | None  (None when absent or ambiguous, e.g. "m/f").

Keep this in sync with the Dart mirror used for defensive runtime normalization.
"""
from __future__ import annotations

import re

# The canonical, language-neutral set. UI translations are keyed `pos.<tag>`.
TAGS = (
    "noun", "verb", "adjective", "adverb", "pronoun", "preposition",
    "conjunction", "numeral", "interjection", "article", "other",
)

# Head token (first word of the raw pos) -> canonical tag.
_HEAD = {
    "noun": "noun", "n": "noun",
    "verb": "verb", "v": "verb", "aux": "verb", "auxiliary": "verb",
    "adjective": "adjective", "adj": "adjective",
    "adverb": "adverb", "adv": "adverb",
    "pronoun": "pronoun", "pron": "pronoun",
    "preposition": "preposition", "prep": "preposition",
    "conjunction": "conjunction", "conj": "conjunction", "connector": "conjunction",
    "numeral": "numeral", "num": "numeral", "number": "numeral",
    "interjection": "interjection", "interj": "interjection",
    "article": "article", "art": "article", "determiner": "article",
    "particle": "other", "classifier": "other", "other": "other",
}

# Contracted head tokens that also carry gender (e.g. "nm" = noun, masculine).
_HEAD_GENDER = {
    "nm": ("noun", "m"),
    "nf": ("noun", "f"),
}

# Trailing gender markers. Bare "n" is intentionally excluded — it means "noun"
# as a head, and neuter is spelled out ("neut"/"neuter") in the data.
_GENDER = {
    "m": "m", "masc": "m", "masculine": "m",
    "f": "f", "fem": "f", "feminine": "f",
    "neut": "n", "neuter": "n",
}

# Whole-string aliases for pos values the tokenizer can't reach — non-Latin
# scripts (Vietnamese "từ" is outside the a-ÿ range) and other target-language
# leakage. Extend as new languages surface untranslated grammar terms.
_FULL_ALIAS = {
    "danh từ": ("noun", None),
}

_TOKEN = re.compile(r"[a-zà-ÿ]+")


def normalize(raw):
    """Return (tag, gender) for a free-text pos string. See module docstring."""
    if not raw or not str(raw).strip():
        return ("other", None)
    s = str(raw).strip().lower()

    alias = _FULL_ALIAS.get(s)
    if alias is not None:
        return alias

    toks = _TOKEN.findall(s)
    if not toks:
        return ("other", None)

    head = toks[0]
    if head in _HEAD_GENDER:
        return _HEAD_GENDER[head]

    tag = _HEAD.get(head, "other")

    genders = {_GENDER[t] for t in toks[1:] if t in _GENDER}
    gender = next(iter(genders)) if len(genders) == 1 else None

    return (tag, gender)
